apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service
  namespace: production
  labels:
    app: user-service
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - user-service
      - key: version
        operator: In
        values:
          - blue
          - green
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: student-service
  namespace: production
  labels:
    app: student-service
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - student-service
      - key: version
        operator: In
        values:
          - blue
          - green
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lecturer-service
  namespace: production
  labels:
    app: lecturer-service
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - lecturer-service
      - key: version
        operator: In
        values:
          - blue
          - green
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: course-service
  namespace: production
  labels:
    app: course-service
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - course-service
      - key: version
        operator: In
        values:
          - blue
          - green
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: enrollment-service
  namespace: production
  labels:
    app: enrollment-service
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - enrollment-service
      - key: version
        operator: In
        values:
          - blue
          - green
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
